### ISSUE TITLE
step 1

### ISSUE THREAD

**Issue by cagojeiger** [kangheeyong/PROJECT-personal-recommendation-system-demo#1]

**Comment by cagojeiger** [comment]
# step 1 기록들

## 시스템 설계 관련
- [step 1의 청사진](https://github.com/kangheeyong/PROJECT-personal-recommendation-system-demo/issues/1#issuecomment-597536741)
- [가상 유저 생성 방법](https://github.com/kangheeyong/PROJECT-personal-recommendation-system-demo/issues/1#issuecomment-604235101)
- [toy system 프로그램 관련 요약](https://github.com/kangheeyong/PROJECT-personal-recommendation-system-demo/issues/1#issuecomment-604235209)


---

## mongDB 설계 관련
- [mongDB : model One-to-N relationships(document level) 정리](https://github.com/kangheeyong/PROJECT-personal-recommendation-system-demo/issues/1#issuecomment-607273980)
- [mongDB : model One-to-N relationships(document level) 분석](https://github.com/kangheeyong/PROJECT-personal-recommendation-system-demo/issues/1#issuecomment-607577833)

---

## 기타

---

**Comment by cagojeiger** [comment]
# step 1의 청사진 


## 시작하며
2달 동안(2020.1~2) 카카오 추천팀 인턴을 하면서 느낀것은 실제 서비스를 통해서 배울 수 있는게 있다는 것이다. 그중 가장 핵심은 실제 서비스의 피드백이다. 개인은 서비스를 갖기 힘들기 때문에 쉽게 배울 수 없는 것이다. 그러면 개인이 실제 서비스를 갖는 방법은 없는걸까? 

잘 생각해보면 머신러닝에서는 MNist와 같이 toy data가 있다. 그렇다면 toy system을 만들면 되는게 아닌가?? 

문제는 어떻게 시작하고 만드는가?이다. 처음부터 완벽하게 설계하는 건 무리이기 때문에 가장 먼저 가상의 유저를 만들고 그 유저와 소통하는 가상 app을 만들것이다. 이것이 있어야 데이터를 모으고, 그 데이터를 분석해서 머신러닝 모델을 만들 수 있을 것이다. 

## 설계도
<img width="644" alt="스크린샷 2020-03-11 오후 5 42 06" src="https://user-images.githubusercontent.com/18637774/76398106-a2d51b80-63bf-11ea-89de-8d37542172a6.png">

위의 그림은 가상의 유저와 가상의 app이 서로 어떻게 소통을 하는지 보여주는 그림이다. 상황은 개인화 추천이고, app은 유튜브라고 생각하면 된다. 
  1. 먼저 유저가 app(유튜브와 같은)에 접속을 시도하면 유저 id가 app에 전달 된다.
  1. 유저 id를 통하여 개인화 추천을 만들고, 유저에게 아이템 id를 전달한다.
  1. 아이템 id를 받은 유저는 추천된 아이템 id를 선택하거나, 특정 아이템 id를 찾아서 선택하거나, 아무것도 하지 않는다. 이 결과를 다시 app에 전달한다.

이제 위와 같은 순서가 반복이 된다.

---
<img width="787" alt="스크린샷 2020-03-11 오후 5 42 24" src="https://user-images.githubusercontent.com/18637774/76398130-ad8fb080-63bf-11ea-98b3-9fc9032328ab.png">

위의 사진은 실제 코드 관련 구조이다. 여기서 실행되는 프로그램은 demo_user.py와 demo_app.py이다. 가상의 유저는 특정 확률 분포를 이용하여 미리 정의하고 샘플링하여 데이터를 생성한다. 그리고 app에서도 backend에서 만든 추천 결과를 가지고 추천 리스트를 만들고 유저의 피드백을 kafka 서버로 전송할 것이다. 여기서 추천 결과는 일단 임의로 만들 것이다.

**Comment by cagojeiger** [comment]
# 가상 유저 생성 방법

## 기본 수학적 가정

<img width="557" alt="스크린샷 2020-03-26 오후 3 06 43" src="https://user-images.githubusercontent.com/18637774/77615736-68e54700-6f73-11ea-8b17-b321cf46095d.png">

유저의 성향을 위와 같이 모델링한 이유는 Matrix Factorization과 같은 형태이기 때문이다.

## 알고리즘

<img width="824" alt="스크린샷 2020-03-26 오후 3 26 37" src="https://user-images.githubusercontent.com/18637774/77616918-2ffaa180-6f76-11ea-9eb6-28061400a399.png">

1. 먼저 15초의 주기로 유저 수를 포아송 분포로 샘플링한다. 그 후 균일 분포로 유저를 생성한다.
1. 그후 3가지 케이스로 나뉜다.
   1. 아무것도 하지 않는다.
   1. 유저가 직접 아이템을 찾아서 선택한다.
   1. 추천 리스트 중 하나를 선택한다. 
1. 다시 1번으로 돌아간다.

## 추천 리스트 중 하나를 선택하는 방법
<img width="864" alt="스크린샷 2020-03-26 오후 3 19 02" src="https://user-images.githubusercontent.com/18637774/77616494-2290e780-6f75-11ea-878f-8a3832036f36.png">

유저가 추천 아이템을 선택하는 방법은 미리 정의된 유저 파라메터의 상위 1000개의 아이템 중 실제 추천 리스트에 포함되는 아이템이 있으면 그 아이템을 선택한다. 만약 여러게가 있다면, 임의로 하나를 선택한다.

**Comment by cagojeiger** [comment]
# toy system 프로그램 관련 요약

<img width="1273" alt="스크린샷 2020-03-26 오후 2 29 08" src="https://user-images.githubusercontent.com/18637774/77613480-2a00c280-6f6e-11ea-9f9f-65c7875b6890.png">

- 파일 저장 관련
  - kafka : 유저의 피드백을 임시로 저장한다.
  - mongDB : 유저의 피드백 데이터를 어느정도 전처리하여 저장한다.
  - google drive : 모델의 파라메터를 저장한다. 
- 파이썬 코드 관련
  - demo_user.py : 유저를 생성하고 추천 결과에 따른 피드백을 만들어 준다.
  - demo_app.py : 유저id를 받으면 유저id에 따른 추천 결과를 만들어주며, 유저의 피드백을 kafka서버에 저장한다.
  - demo_dist.py : kafka에 저장된 유저 피드백 데이터를 몽고디비에 저장한다.
  - demo_gc.py : mongDB에서 유저 피드백 정보를 읽어서 추천 목록을 만든다.
    - 추천 알고리즘은 유저가 선택한 아이템과 클릭한 아이템 수가 가장 많은 아이템을 추천 결과로 만든다.
  - observe.py : supervisord에서 프로세스 상태가 변하면 slack으로 메세지를 보낸다.
  - slack_bot.py : ctr 결과를 slack으로 메세지를 보낸다.
- 기타
  - supervisord : 프로세스 모니터링
  - slack : 알림
  - docker : 개발 환경 저장
  - sanic : 비동기 웹 프레임워크

**Comment by cagojeiger** [comment]
# mongDB : model One-to-N relationships(document level) 정리


데이터베이스에 대한 개념이 없는 초보는 공부를 어떻게 시작해야 되는지 정말 막막하다. 게다가 일반적으로 많이 사용된 관계형 데이터베이스와 다른 구조 개념을 가지고 있고, 사용된 기간이 상대적으로 짧아서 한국어 자료가 많지 않다. 그래서 [공식 홈페이지](https://www.mongodb.com)의 관련 글을 보고 공부할 수 밖에 없었다. 그리고 개인적인 경험으로는 어설프게 구글링하는 것 보다 의외로 공식 홈페이지에서 제공하는 관련 글들이 퀄리티가 굉장히 좋았다. 

몽고디비를 공부하기 위해서 가장 가장 작은 단위의 저장 단위인 document를 일반적으로 어떻게 쓰는지 알아보았다. 이렇게 시작한 이유는 가장 작은 단위의 사용법에서 점점 위로 올라가서 큰그림이 어떻게 그려지는지 직접 경험하기 위해서이다. 

먼저 몽고디비의 가장 작은 단위의 저장 단위인 documents의 저장 용량이 16MB이다. 이러한 특성을 가지고 있어서 documents를 설계하는데 다음과 같이 3가지 방법이 있다고 한다.
- One-to-few
- One-to-many
- One-to-Squillions

이제 위의 구조가 실제로 어떻게 설계되는지 알아보겠다.

### 1. One-to-few

<img width="433" alt="스크린샷 2020-04-02 오후 6 11 11" src="https://user-images.githubusercontent.com/18637774/78231152-576ce380-750d-11ea-9bb6-6b497a906740.png">

위의 예시는 어떤 post에 comment가 달린 글의 예시이다. 여기서 one은 post를 의미하고 few는 comment를 의미한다. 만약 comment가 많이 없다면 위와 같은 구조로 설계하면 된다. 여기서 장점은 하나의 collection을 사용하기때문에 검색이 용이하다.

### 2. One-to-many

<img width="445" alt="스크린샷 2020-04-02 오후 6 12 06" src="https://user-images.githubusercontent.com/18637774/78231243-78cdcf80-750d-11ea-838c-aebfb1347a48.png">

<img width="439" alt="스크린샷 2020-04-02 오후 6 12 21" src="https://user-images.githubusercontent.com/18637774/78231271-81260a80-750d-11ea-8c22-c25a5107b3c4.png">

만약 comment의 양이 많다면 위와 같이 설계할 수 있다.  post에는 다른 collection에 저장한 comment의 id를 저장한다. 이렇게 하면 one-to-few보다 더 많은 comment를 저장할 수 있다. 데이터를 모두 읽는 경우는 아래와 같다.

<img width="709" alt="스크린샷 2020-04-02 오후 6 24 27" src="https://user-images.githubusercontent.com/18637774/78232424-32797000-750f-11ea-8d47-81d286d97b9b.png">

위와 같은 방식은 일반 적으로 application-level join이라고 한다. 관계형 데이터베이스에는 서로 다른 table(몽고에서는 collection)을 join이라는 쿼리문을 이용해서 한번에 값을 요청할 수 있지만 몽고디비에서는 할 수 없다. 그렇기 때문에 위와 같이 application-level에서 join을 해야한다.

### 3. One-to-squillions

<img width="440" alt="스크린샷 2020-04-02 오후 6 13 16" src="https://user-images.githubusercontent.com/18637774/78231353-a155c980-750d-11ea-90c0-3ad8d8e29769.png">

<img width="447" alt="스크린샷 2020-04-02 오후 6 13 30" src="https://user-images.githubusercontent.com/18637774/78231373-aa469b00-750d-11ea-90c2-3d7b5f8f3cbc.png">

만약 comment의 양이 엄청? 많다면 위와 같이 설계할 수 있다.  post는 한번만 업데이트가 되고 comment가 추가 될 때 post의 id를 추가해서 저장하면 된다. 

<img width="913" alt="스크린샷 2020-04-02 오후 7 35 55" src="https://user-images.githubusercontent.com/18637774/78239844-2eeae680-7519-11ea-8267-9d6a2f0a43d2.png">

데이터를 읽는 방법은 위와 같다. 위의 코드에서 sort와 limit가 있는 이유는 이 케이스는 엄청 많은 comment가 있다고 가정한 케이스이기 때문에 일부만 불러오게 했다. 만약 전부 불러오고 싶다면 sort와 limit를 빼면 된다.

## 마무리

몽고디비에서 document level 설계를 할 때 어떤 경우가 있는지 알아보았다. 다음 글은 어떤 상황에서 어떻게 설계하는게 좋은지 분석해보겠다.

## 다음글
- [mongDB : model One-to-N relationships(document level) 분석](https://github.com/kangheeyong/PROJECT-personal-recommendation-system-demo/issues/1#issuecomment-607577833)

## reference

- [몽고디비 설명](https://m.blog.naver.com/gkenq/10184665342)
- [MongoDB 스키마 디자인을 위한 6가지 규칙 요약(한글)](https://edykim.com/ko/post/summary-of-six-rules-for-designing-a-mongodb-schema/)
- [6 Rules of Thumb for MongoDB Schema Design: Part 1](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-1)

**Comment by cagojeiger** [comment]
# mongDB : model One-to-N relationships(document level) 분석

이번 글은 [6 Rules of Thumb for MongoDB Schema Design: Part 3](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-3)에서 언급한 아래의 내용을 바탕으로 몽고디비에서 document level을 어떻게 설계하는지 분석 해보겠다.

<img width="763" alt="스크린샷 2020-04-02 오후 7 48 56" src="https://user-images.githubusercontent.com/18637774/78241203-fea44780-751a-11ea-98e5-0b4ff21927ab.png">

위의 글을 정리해보면 아래와 같다.(~~틀릴수도 있다...~~)
  - 가능하면 하나의 document에 모두 저장하자!!! (몽고디비는 join 기능이 없다.)
  - document에 저장된 다른 document의 id를 다시 읽을 짓을 피하자!!! (2번 read) 
  - document 내에서 동적 배열이나 너무 많은  document 또는 id를 넣는 것을 피하자!!! (몽고디비의 성능 저하를 가져오는 것 같음.)

이제 하나하나 분석해보자.

## 1. One-to-few

다른 collection 간의 join이 없는 몽고디비 입장에서는 가장 심플하고 강력한 구조인것 같다. 검색과 쓰기, 삭제가 한번의 명령어로 끝난다. 여기서 주의해야 할 것은 한번 업데이트가 되고 document 내의 정보가 처음에 만들었을 때보다 양이 증가한다면 이 구조는 적합한 구조가 아닐 것이다. 

## 2. One-to-many

이 구조의 경우 document 내에 저장되는 document의 크기가 엄청 크다면(16MB 이상?) 적합한 구조인것 같다. 하지만 이 구조도 document 내에 저장되는  document가 처음에 만들었을 때보다 양이 증가 한다면 이 구조는 적합한 구조가 아닐 것이다.

## 3. One-to-squillions

이 구조의 경우 document 내에 저장되는  document가 처음에 만들었을 때보다 양이 증가 한다면 이 구조는 적합할 것이다. 다만 문제점은 부모가 되는 document에서 자식 document 정보를 알 수 없다는 단점이 있다.

## 요약
 
 가장 먼저 one-to-few 구조를 고려해야하고, 그 다음에 one-to-squillions 구조를 고려하면 된다. 만약 document 내에 저장되는 document의 크기가 크고 새롭게 추가 되는 것이 없다면 one-to-many 구조가 적합할 것이다. 만약 좀 더 응용된 구조가 궁금하다면 [6 Rules of Thumb for MongoDB Schema Design: Part 2](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-2)를 참고하면 된다.

## reference
- [비정규화 이야기](http://wiki.gurubee.net/pages/viewpage.action?pageId=28606676)
- [6 Rules of Thumb for MongoDB Schema Design: Part 2](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-2) 
- [6 Rules of Thumb for MongoDB Schema Design: Part 3](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-3)

**Comment by kangheeyong** [comment]
# mongDB : Two-Way Referencing and Denormalizing (document level)


- [비정규화 이야기](http://wiki.gurubee.net/pages/viewpage.action?pageId=28606676)
- [6 Rules of Thumb for MongoDB Schema Design: Part 2](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-2) 
- [6 Rules of Thumb for MongoDB Schema Design: Part 3](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-3)

**Comment by kangheeyong** [comment]
# mongDB : Two-Way Referencing and Denormalizing (document level)


- [비정규화 이야기](http://wiki.gurubee.net/pages/viewpage.action?pageId=28606676)
- [6 Rules of Thumb for MongoDB Schema Design: Part 2](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-2) 
- [6 Rules of Thumb for MongoDB Schema Design: Part 3](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-3)
